const wordList = ['among us', 'imposter', 'america', 'britain', 'weeb', 'John F Kennedy', 'Samurai', 'Ninja', 'Viking', 'Knight', 'Jew', 'Darth Vader', 'Magic', 'Bowling', 'porn', 'shitting in the tall grass', 'death star', 'thanos', 'baby yoda', 'praise the sun', 'dead by daylight', 'benis', 'bussy', 'communist superman', 'bully maguire', 'amish', 'hoes mad', 'pirates', 'colonialism', 'facism', 'censorship', 'hebrew hot dog', 'torah', 'bible', 'quran', 'buddha', 'nationalism', 'subjective', 'nazi', 'adolf hitler', 'nerd', 'dork', 'jump', 'ouija', 'tank', 'anakin', 'bunny', 'necrophilia', 'adventure time', 'black mario', 'chad', 'zombie', 'batman', 'joker', 'spongebob', 'empty', 'instagram', 'youtube', 'facebook', 'super smash bros', 'discord', 'zelda', 'pizza hut', 'dominos', 'time', 'space', 'rock', 'nothing', 'spider', 'draw', 'cure', 'vaccine', 'covid 19', 'trump', 'biden', 'record', 'attack', 'logo', 'religion', 'crime', 'prison', 'statistic', 'law', 'download', 'taxi', 'yolk', 'RV', 'irrational', 'danger', 'memory', 'atlantis', 'martian manhunter', 'iron man', 'art', 'society', 'horny jail', 'hells kitchen', 'kitchen nightmares', 'gordan ramsay', 'jojo', 'blowjob', 'raining cats and dogs', 'purple', 'smooch', 'star wars', 'backflip', 'onlyfans', 'twitter', 'bitch', 'minecraft', 'creeper', 'zombie pigman', 'dragon', 'witch', 'runescape', 'justice league', 'hulk', 'godzilla', 'mecha godzilla', 'king kong', 'kirby', 'link', 'banana', 'sheev', 'step brother', 'step dad', 'step mom', 'ghost', 'mirror', 'snapchat', 'dennys', 'pewdiepie', 'root beer', 'beach', 'music', 'noise', 'mute', 'hydra', 'africa', 'pakistan', 'russia', 'china', 'japan', 'yoda', 'gandolf', 'sauron', 'frodo', 'golem', 'naruto', 'shuriken', 'kunai', 'shit', 'mace windu', 'Aayla Secura', 'god', 'jetpack', 'fish', 'flamingo', 'window', 'email'];
const backup = ['among us', 'imposter', 'america', 'britain', 'weeb', 'John F Kennedy', 'Samurai', 'Ninja', 'Viking', 'Knight', 'Jew', 'Darth Vader', 'Magic', 'Bowling', 'porn', 'shitting in the tall grass', 'death star', 'thanos', 'baby yoda', 'praise the sun', 'dead by daylight', 'benis', 'bussy', 'communist superman', 'bully maguire', 'amish', 'hoes mad', 'pirates', 'colonialism', 'facism', 'censorship', 'hebrew hot dog', 'torah', 'bible', 'quran', 'buddha', 'nationalism', 'subjective', 'nazi', 'adolf hitler', 'nerd', 'dork', 'jump', 'ouija', 'tank', 'anakin', 'bunny', 'necrophilia', 'adventure time', 'black mario', 'chad', 'zombie', 'batman', 'joker', 'spongebob', 'empty', 'instagram', 'youtube', 'facebook', 'super smash bros', 'discord', 'zelda', 'pizza hut', 'dominos', 'time', 'space', 'rock', 'nothing', 'spider', 'draw', 'cure', 'vaccine', 'covid 19', 'trump', 'biden', 'record', 'attack', 'logo', 'religion', 'crime', 'prison', 'statistic', 'law', 'download', 'taxi', 'yolk', 'RV', 'irrational', 'danger', 'memory', 'atlantis', 'martian manhunter', 'iron man', 'art', 'society', 'horny jail', 'hells kitchen', 'kitchen nightmares', 'gordan ramsay', 'jojo', 'blowjob', 'raining cats and dogs', 'purple', 'smooch', 'star wars', 'backflip', 'onlyfans', 'twitter', 'bitch', 'minecraft', 'creeper', 'zombie pigman', 'dragon', 'witch', 'runescape', 'justice league', 'hulk', 'godzilla', 'mecha godzilla', 'king kong', 'kirby', 'link', 'banana', 'sheev', 'step brother', 'step dad', 'step mom', 'ghost', 'mirror', 'snapchat', 'dennys', 'pewdiepie', 'root beer', 'beach', 'music', 'noise', 'mute', 'hydra', 'africa', 'pakistan', 'russia', 'china', 'japan', 'yoda', 'gandolf', 'sauron', 'frodo', 'golem', 'naruto', 'shuriken', 'kunai', 'shit', 'mace windu', 'Aayla Secura', 'god', 'jetpack', 'fish', 'flamingo', 'window', 'email'];
function getWord(){
    if(wordList.length == 0)
    {
        for (var i of backup) {
            wordList.push(i);
        }
         
    }
    var index = Math.floor(Math.random() * wordList.length)
    var word = wordList[index].toLowerCase();
    wordList.splice(index, 1);
    return word;
}

module.exports = { 
    getWord
};